Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,4 +1,4 @@
-name: Docker Image CI - Orchestrator
+name: Docker Image CI/CD - Orchestrator
 
 env:
   DOCKER_IMAGE: orchestrator
@@ -35,3 +35,27 @@ jobs:
 
     - name: Push the Docker image
       run: docker push ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:latest
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build-and-push-image
+    steps:      
+      - name: SSH into VM and Deploy new Image with Docker
+        uses: appleboy/ssh-action@v1.2.0
+        with:
+          host: ${{ secrets.VM_HOST_IP }}
+          username:  ${{ secrets.VM_USER }}
+          key: ${{ secrets.VM_SSH_KEY }}
+          script: |
+            # Fail script on first error
+            set -e 
+            # Login to GitHub Container Registry
+            echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+            
+            # Deploy new Image
+            cd /root/modapto/orchestrator
+            docker compose pull ${{ env.DOCKER_IMAGE }}
+            docker compose up -d --no-deps ${{ env.DOCKER_IMAGE }}
+
+            # Loggout
+            docker logout ghcr.io
